# Generated by Django 6.1.1 on 2026-09-26 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('politicians', '0002_alter_politician_fec_candidate_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('degraded', 'Degraded'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('topics', models.JSONField(default=list)),
                ('force_refresh', models.BooleanField(default=False)),
                ('task_result_id', models.CharField(blank=True, default='', max_length=64)),
                ('credits', models.PositiveIntegerField(default=0)),
                ('stats', models.JSONField(blank=True, default=dict)),
                ('error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('politician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='research_runs', to='politicians.politician')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SourceCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adapter', models.CharField(max_length=20)),
                ('topic', models.CharField(blank=True, default='', max_length=30)),
                ('endpoint', models.CharField(max_length=500)),
                ('query', models.CharField(blank=True, default='', max_length=500)),
                ('credits', models.PositiveSmallIntegerField(default=0)),
                ('latency_ms', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('ok', 'Ok'), ('error', 'Error')], default='ok', max_length=10)),
                ('error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='source_calls', to='research.researchrun')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='researchrun',
            index=models.Index(fields=['politician', '-created_at'], name='research_re_politic_59b4ad_idx'),
        ),
    ]
