# Generated by Django 6.1.1 on 2026-09-26 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Politician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('party', models.CharField(blank=True, default='', max_length=100)),
                ('office', models.CharField(blank=True, default='', max_length=100)),
                ('state', models.CharField(blank=True, default='', max_length=2)),
                ('fec_candidate_id', models.CharField(blank=True, default='', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('name', 'office', 'state'), name='politician_identity')],
            },
        ),
        migrations.CreateModel(
            name='PoliticianProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('federal', 'Federal')], max_length=20)),
                ('summary', models.TextField()),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('politician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='politicians.politician')),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='SourceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('tavily_web', 'Tavily Web'), ('tavily_news', 'Tavily News'), ('fec', 'Fec')], max_length=20)),
                ('topic', models.CharField(max_length=30)),
                ('url', models.CharField(max_length=500)),
                ('url_hash', models.CharField(max_length=64)),
                ('title', models.CharField(blank=True, default='', max_length=500)),
                ('content', models.TextField(blank=True, default='')),
                ('first_hand', models.BooleanField(default=False)),
                ('published_date', models.DateField(blank=True, null=True)),
                ('retrieved_at', models.DateTimeField()),
                ('fresh_until', models.DateTimeField()),
                ('politician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_records', to='politicians.politician')),
            ],
            options={
                'ordering': ['-retrieved_at'],
            },
        ),
        migrations.CreateModel(
            name='Fact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(choices=[('positions', 'Positions'), ('voting_record', 'Voting Record'), ('controversies', 'Controversies'), ('donations', 'Donations')], max_length=30)),
                ('claim', models.TextField()),
                ('quote', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facts', to='politicians.politicianprofile')),
                ('source_record', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='facts', to='politicians.sourcerecord')),
            ],
            options={
                'ordering': ['profile', 'topic', 'pk'],
            },
        ),
        migrations.AddConstraint(
            model_name='politicianprofile',
            constraint=models.UniqueConstraint(fields=('politician', 'scope'), name='profile_scope_unique'),
        ),
        migrations.AddIndex(
            model_name='sourcerecord',
            index=models.Index(fields=['politician', 'source_type', 'topic', 'fresh_until'], name='src_cell_fresh_idx'),
        ),
        migrations.AddConstraint(
            model_name='sourcerecord',
            constraint=models.UniqueConstraint(fields=('politician', 'source_type', 'topic', 'url_hash'), name='source_cell_unique'),
        ),
    ]
