# Generated by Django 6.1.1 on 2026-09-26 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('politicians', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='politician',
            name='fec_candidate_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
