# Generated by Django 6.1.1 on 2026-09-26 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('politicians', '0002_alter_politician_fec_candidate_id'),
        ('research', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='politicianprofile',
            name='research_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles', to='research.researchrun'),
        ),
    ]
