# Generated by Django 6.1.1 on 2026-09-20 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('profiler', 'Profiler'), ('researcher', 'Researcher'), ('summarizer', 'Summarizer'), ('matcher', 'Matcher'), ('recommender', 'Recommender'), ('judge', 'Judge')], max_length=20)),
                ('model', models.CharField(max_length=200)),
                ('base_url', models.CharField(max_length=500)),
                ('prompt_name', models.CharField(blank=True, default='', max_length=100)),
                ('prompt_version', models.CharField(blank=True, default='', max_length=32)),
                ('response_format', models.CharField(choices=[('text', 'Text'), ('json_mode', 'Json Mode'), ('json_schema', 'Json Schema')], default='text', max_length=20)),
                ('attempts', models.PositiveSmallIntegerField(default=1)),
                ('prompt_tokens', models.IntegerField(blank=True, null=True)),
                ('completion_tokens', models.IntegerField(blank=True, null=True)),
                ('total_tokens', models.IntegerField(blank=True, null=True)),
                ('latency_ms', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('ok', 'Ok'), ('error', 'Error')], default='ok', max_length=10)),
                ('error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['role', 'created_at'], name='llm_modelca_role_760890_idx')],
            },
        ),
    ]
